language: python
os: linux
dist: xenial
sudo: required

compiler: gcc
packages:
  - cmake

# GitHub branch
branches:
  only:
    - master

# build jobs
jobs:
  include:
    - python: 3.6
    - stage: deploy
      install:
        - pip install sphinx sphinx-rtd-theme sphinxcontrib-bibtex numpydoc==0.9.2 travis-sphinx
      script:
        - sphinx-apidoc -feo docs/source mccd
        - travis-sphinx -v -o docs/build build -n -s docs/source
      after_success:
        - travis-sphinx -o docs/build deploy

# update pre-installed packages
before_install:
  - pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U

# install dependencies
install:
  - pip install numpy future scipy progressbar2
  - pip install coverage nose pytest pytest-cov pytest-pep8
  - pip install scikit-learn scikit-image
  - pip install matplotlib
  - pip install pybind11
  - pip install astropy
  - pip install termcolor
  - pip install galsim
  - pip install modopt
  - pip install python-pysap

# run unit tests
script:
  - python setup.py test

# notification settings
notifications:
  email: false