language: python
os: linux
dist: xenial
sudo: required

compiler:
    - gcc
packages:
  - cmake

# GitHub branch
branches:
  only:
    - master

# build jobs
jobs:
  include:
    - python: 3.6
      env:
        - COMPILER=gcc
        - CC=gcc
        - CXX=g++
      name: Linux gcc (Python 3.6)

    - stage: deploy
      install:
        - pip install sphinx sphinx-rtd-theme sphinxcontrib-bibtex numpydoc==0.9.2 travis-sphinx
      script:
        - sphinx-apidoc -feo docs/source mccd
        - travis-sphinx -v -o docs/build build -n -s docs/source
      after_success:
        - travis-sphinx -o docs/build deploy

# update pre-installed packages
before_install:
  - pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
  - sudo -H apt-get -qq update
  - sudo updatedb
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - export CPLUS_INCLUDE_PATH=$(cd /opt/python/3.*/include/python3.*; pwd)
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  - conda update --all -y;
  - conda info -a
  - sudo -H apt-get install -y python-dev libfftw3-dev libav-tools libeigen3-dev

# install dependencies
install:
  - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - pip install --upgrade pip
  - python --version
  - pip --version
  - locate pyconfig.h
  - pip install numpy cython
  - pip install setuptools
  - pip install future scipy progressbar2
  - pip install coverage nose pytest pytest-cov pytest-pep8
  - pip install scikit-learn scikit-image
  - pip install matplotlib
  - pip install pybind11
  - pip install astropy
  - pip install termcolor
  - pip install modopt
  - pip install sf_tools
  - pip install python-pysap
  - pip install galsim

# run unit tests
script:
  - python setup.py test

# notification settings
notifications:
  email: false