name: CD

on:
  push:
    branches:
     - master
  pull_request:
    branches:
      - master

jobs:

  coverage:
    name: Deploy Coverage Results
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install macOS Dependencies
        if: runner.os == 'macOS'
        run: |
          brew tap sfarrens/sf
          brew install bigmac libomp

      - name: Check Python Version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r develop.txt
          python -m pip install twine
          python -m pip install PyQt5
          python -m pip install pyqtgraph
          python -m pip install git+https://github.com/CEA-COSMIC/pysap.git@2e26a71024b5a0419b27d4b3fc5cdee77bd3919b
          python -m pip install GalSim

      - name: Install requirements
        run: |
          python -m pip install -r docs/requirements.txt

      - name: Install MCCD
        run: python -m pip install .

      - name: Run Tests
        run: |
          python setup.py test

      - name: Check distribution
        run: |
          python setup.py sdist
          twine check dist/*

  api:
    name: Deploy API Documentation
    needs: coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install macOS Dependencies
        if: runner.os == 'macOS'
        run: |
          brew tap sfarrens/sf
          brew install bigmac libomp

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandoc
          python -m pip install pyqtgraph
          python -m pip install git+https://github.com/CEA-COSMIC/pysap.git@2e26a71024b5a0419b27d4b3fc5cdee77bd3919b
          python -m pip install -r docs/requirements.txt
          python -m pip install GalSim
          python -m pip install .

      - name: Build API documentation
        run: |
          sphinx-apidoc -t docs/_templates -feTMo docs/source mccd
          sphinx-build -E docs/source docs/_build

      - name: Deploy API documentation
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build

